categories/urls.py
from django.urls import path
from . import views

# Create a namespace for these urls
# categories:<path_name>
app_name = 'categories'

urlpatterns = [
    path('', views.CategoryList.as_view(), name='list'),
    path('categorias', views.CategoryList.as_view(), name='list'),
    path('categorias/<str:slug>', views.CategoryChildren.as_view(), name='children'),
    path('categorias/<str:parent>/<str:slug>', views.CategoryDetails.as_view(), name='details'),
]

levoemcasa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('categories.urls')),
    path('loja/', include('store.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

store/urls.py
from django.urls import path, include
from . import views
from products.views import ProductDetails

# Create a namespace for these urls
# store:<path_name>
app_name = 'store'

urlpatterns = [
    # path('', views.StoreList.as_view(), name='list'),
    path('<str:slug>', views.StoreDetails.as_view(), name='list'),
    path('<str:store>/<str:slug>', ProductDetails.as_view(), name='details'),
    # path('category/<str:slug>', views.CategoryChildren.as_view(), name='children'),
    # path('category/<str:parent>/<str:slug>', views.CategoryDetails.as_view(), name='details'),
]

categories/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nome')
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.DO_NOTHING)
    slug = models.SlugField(unique=True)
    summary = models.CharField(max_length=255, verbose_name='Resumo')
    description = models.TextField(verbose_name='Descricao')
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

categories/views.py
from django.shortcuts import redirect, Http404
from django.shortcuts import render
from django.db.models import Q, Count, Case, When
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.views.generic import TemplateView
from django.views import View
from store.models import Store
from . models import Category


# Create your views here.
class CategoryList(ListView):
    model = Category
    paginate_by = 4
    context_object_name = 'categories'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(parent=None)
        qs = qs.annotate(
            count_stores=Count('store'),
            count_children=Count('children'),
        )
        return qs


class CategoryChildren(ListView):
    model = Category
    paginate_by = 4
    template_name = 'categories/category_children.html'
    context_object_name = 'categories'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('parent')     # Optimized query to get parent data

        # get slug for this category
        slug = self.kwargs.get('slug', None)

        if not slug:
            return qs

        # filter children with this parent's slug
        qs = qs.filter(parent__slug__iexact=slug)
        qs = qs.annotate(
            count_stores=Count('store'),
        )
        return qs


class CategoryDetails(ListView):
    model = Store
    paginate_by = 3
    context_object_name = 'stores'
    template_name = 'categories/category_details.html'

    def get_queryset(self):
        qs = super().get_queryset()

        # get slug for this category
        slug = self.kwargs.get('slug', None)

        # filter stores in this category
        qs = qs.filter(categories__slug__icontains=slug)
        return qs

categories/templates/categories/category_children.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

   <!-- ===== Start of Popular Categories Section ===== -->
    <section class="ptb80" id="categories">
        <div class="container">

            <div class="section-title">
                <h2>sub categorias</h2>
            </div>

            <div class="row nomargin">

                {% for category in categories %}

                <!-- Start of Category div -->
                <div class="col-md-3 col-sm-6 col-xs-12 cat-wrapper">
                    <div class="category ptb30">

                        <!-- Icon -->
                        <div class="category-icon">
                            <i class="fa fa-folder-open"></i>
                        </div>

                        <!-- Category Info - Title -->
                        <div class="category-info pt30">
                            <a href="{% url 'categories:details' category.parent category.slug %}">{{ category.name }}</a>
                            <p>
                                <span>{{ category.count_stores }} loja(s)</span>
                            </p>
                        </div>

                        <!-- Category Description -->
                        <div class="category-descr">
                            <span>{{ category.summary }}</span>
                        </div>

                    </div>
                </div>
                <!-- End of Category div -->

                 {% endfor %}

            </div>

                {% include '_pagination.html' %}

        </div>
    </section>
    <!-- ===== End of Popular Categories Section ===== -->

{% endblock %}

categories/templates/categories/category_details.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

    <!-- ===== Start of Category Details Section ===== -->
    <section class="ptb80" id="latest-news">
        <div class="container">

            <!-- Section Title -->
            <div class="section-title">
                <h2>Lojas Relacionadas</h2>
            </div>

            {% for store in stores %}
            <!-- Start of Blog Post -->
            <div class="col-md-4 col-xs-12">
                <div class="blog-post">

                    {% if store.image %}
                    <!-- Blog Post Image -->
                    <div class="blog-post-thumbnail">
                        <a href="{% url 'store:list' store.slug %}" class="hover-link">
                            <img src="{{ store.image.url }}" alt="{{ store.name }}">
                        </a>
                    </div>
                    {% endif %}

                    <!-- Blog Post Info -->
                    <div class="post-info">
                        <a href="{% url 'store:list' store.slug %}">{{ store.name }}</a>
                        <p>{{ store.slogan }}</p>
                    </div>

                    <!-- Read More Button -->
                    <a href="{% url 'store:list' store.slug %}" class="btn btn-blue btn-small btn-effect">visitar loja</a>

                </div>
            </div>
            <!-- End of Blog Post -->
            {% endfor %}

            {% include '_pagination.html' %}

        </div>
    </section>
    <!-- ===== End of Category Details Section ===== -->

{% endblock %}

categories/templates/categories/category_list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

   <!-- ===== Start of Popular Categories Section ===== -->
    <section class="ptb80" id="categories">
        <div class="container">

            <div class="section-title">
                <h2>categorias principais</h2>
            </div>

            <div class="row nomargin">

                {% for category in categories %}

                <!-- Start of Category div -->
                <div class="col-md-3 col-sm-6 col-xs-12 cat-wrapper">
                    <div class="category ptb30">

                        <!-- Icon -->
                        <div class="category-icon">
                            <i class="fa fa-folder-open"></i>
                        </div>

                        <!-- Category Info - Title -->
                        <div class="category-info pt30">
                            <a href="{% url 'categories:children' category.slug %}">{{ category.name }}</a>
                            <p>
                                <span>{{ category.count_stores }} loja(s)</span>
                                <span>{{ category.count_children }} subcategoria(s)</span>
                            </p>
                        </div>

                        <!-- Category Description -->
                        <div class="category-descr">
                            <span>{{ category.summary }}</span>
                        </div>

                    </div>
                </div>
                <!-- End of Category div -->

                 {% endfor %}

            </div>

                {% include '_pagination.html' %}

        </div>
    </section>
    <!-- ===== End of Popular Categories Section ===== -->

{% endblock %}